<?xml version="1.0"?>
<!-- ####################### -->
<!-- Thats how to write comments -->
<!-- Example Xacro File -->
<!-- ####################### -->

<robot name="differential_drive_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Body Dimensions -->
<xacro:property name="body_link_x_dim" value="1"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<!-- Wheel Dimensions -->
<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>
<!-- Square Wheel Dimensions -->
<xacro:property name="wheel_link_square_edge" value="0.3"/>  <!-- Length of the side of the square -->


<!-- Material Density -->
<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<!-- PI constant -->
<xacro:property name="pi_const" value="3.14159265"/>

<!-- Robot body and wheel mass -->
<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<!-- Robot square wheel mass (using box volume) -->
<xacro:property name="wheel_mass" value="${wheel_density*wheel_link_square_edge*wheel_link_square_edge*wheel_link_length}"/>

<!-- Moments of Inertia of the wheel -->
<!-- Moments of Inertia of the square wheel -->
<xacro:property name="I_wheel_box" value="${(1.0/12.0)*wheel_mass*(2.0*wheel_link_square_edge*wheel_link_square_edge)}"/>



<!-- This macro defines the inertial section of the wheel -->
<xacro:macro name="inertia_wheel">
  <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${I_wheel_box}" ixy="0.0" ixz="0.0" iyy="${I_wheel_box}" iyz="0.0" izz="${I_wheel_box}"/>
  </inertial>
</xacro:macro>


<!-- Over here we include the file that defines extra Gazebo option and robot control driver -->

<xacro:include filename="$(find mobile_robot)/model/robot.gazebo"/>

<!-- ####################### -->
<!-- DEFINE LINKS AND JOINTS -->
<!-- ####################### -->

<!-- necessary dummy -->
<link name="dummy">
</link>
<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link"/>
</joint>


<!-- ####################### -->
<!-- Start: Body link of the robot-->
<!-- ####################### -->


<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia
            ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}"
            ixy="0"
            ixz="0"
            iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}"
            iyz="0"
            izz="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}"/>
    </inertial>
</link>



<!-- ####################### -->
<!-- END: Body link of the robot-->
<!-- ####################### -->



<!-- ####################### -->
<!-- Start: Back right wheel of the robot and the joint-->
<!-- ####################### -->



<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-body_link_x_dim/2 +1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel1_link">
    <visual>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

    <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

    <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </collision>
    
    <xacro:inertia_wheel/>
 </link>   


<!-- ####################### -->
<!-- END:Right back wheel and joint-->
<!-- ####################### -->


<!-- ####################### -->
<!-- Start: Back left wheel of the robot and the joint-->
<!-- ####################### -->

<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-body_link_x_dim/2 +1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
    <visual>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </collision>
    
    <xacro:inertia_wheel/>
</link>   

<!-- ####################### -->
<!-- END: Left back wheel and joint-->
<!-- ####################### -->


<!-- ####################### -->
<!-- Start: Front right wheel of the robot and the joint-->
<!-- ####################### -->

<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="${body_link_x_dim/2 -1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
    <visual>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </collision>
    
    <xacro:inertia_wheel/>
</link>   

<!-- ####################### -->
<!-- END: Right front wheel and joint-->
<!-- ####################### -->


<!-- ####################### -->
<!-- Start: Front left wheel of the robot and the joint-->
<!-- ####################### -->

<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="${body_link_x_dim/2 -1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
    <visual>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </visual>
    
    <collision>
        <geometry>
  <box size="${wheel_link_square_edge} ${wheel_link_square_edge} ${wheel_link_length}"/>
</geometry>

        <origin rpy="${pi_const/2} 0 0" xyz="0 0 0"/>
    </collision>
    
    <xacro:inertia_wheel/>
</link>   

<!-- ####################### -->
<!-- END: Left front wheel and joint-->
<!-- ####################### -->
</robot>

